# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matchrecorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='DCI',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
