# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchrecorder', '0002_auto_20160426_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
